type Dictionary = {
  [locale: string]: {
    [word: string]: string;
  };
};
export const dictionary: Dictionary = {
  en: {
    jumpdog: "Jumpdog",
    play: "Play",
    settings: "Settings",
    nothingHere: "Nothing here",
    switchTheme: "Switch Theme",
    start: "Start",
    kuku: "Kuku",
    guest: "Guest",
    vs: "vs",
    vsCPU: "Play against CPU",
    selectColor: "Color",
    selectLevel: "Level",
    resign: "Resign",
    undo: "Undo",
    redo: "Redo",
    hint: "Hint",
    cancel: "Cancel",
    newGame: "New Game",
    rematch: "Rematch",
    youWon: "You won",
    youLost: "You lost",
    howToPlay: "How to Play",
    dismiss: "Dismiss",
    takeGuide: "Take Guide",
    highlightLastMove: "Highlight last move",
    showLegalMoves: "Show legal moves",
    showCoordinates: "Show coordinates",
    playSounds: "Play sounds",
    darkMode: "Dark mode",
    boardColor: "Board color",
    language: "Language",
    english: "English",
    german: "Deutch",
    arabic: "العربية",
    gray: "Gray",
    blue: "Blue",
    pink: "Pink",
    resignConfirmation: "Are you sure you want to resign?",
    takeTutorial:
      "Jumpdog has few simple rules. Would you like to take a one-time interactive guide on how to play.",
    onCaptureHelp:
      "To capture your opponent, you hop over them and land in the next square.",
    normalMoveHelp:
      "Pieces can move only one square either horizantally or vertically. No diagonal movements.",
  },
  ar: {
    jumpdog: "نط الكلب",
    play: "اِلعب",
    settings: "الاعدادات",
    nothingHere: "لاشيء هنا",
    switchTheme: "اقلب المظهر",
    start: "إبدا",
    kuku: "كُوكُو",
    guest: "أنت",
    vs: "ضد",
    vsCPU: "العب ضد الكومبيوتر",
    selectColor: "اللون",
    selectLevel: "المستوى",
    resign: "انسحب",
    undo: "تراجع",
    redo: "تقدم",
    hint: "تلميح",
    cancel: "الغاء",
    newGame: "لعبة جديدة",
    rematch: "اعادة",
    youWon: "فزت",
    youLost: "خسرت",
    howToPlay: "كيفية اللعب",
    dismiss: "لا",
    takeGuide: "ارني كيف",
    highlightLastMove: "ظلل الحركة الاخيرة",
    showLegalMoves: "اظهر الحركات القانونية",
    showCoordinates: "اظهر الاحداثيات",
    playSounds: "تشغيل الاصوات",
    darkMode: "اللون الداكن",
    boardColor: "لون الطاولة",
    language: "اللغة",
    english: "English",
    german: "Deutch",
    arabic: "العربية",
    gray: "رمادي",
    blue: "ازرق",
    pink: "وردي",
    resignConfirmation: "هل انت متأكد انك تود الانسحاب؟",
    takeTutorial:
      "للعبة قواعد بسيطة. هل تود ان تاخذ ارشادات تفاعلية لاول مرة فقط.",
    onCaptureHelp:
      "لتاخذ قطعة الخصم، تقوم قطعتك بالقفز من فوقه وتهبط في المربع التالي.",
    normalMoveHelp: "تتحرك القطع بمدى مربع واحد اما افقياً او راسياً.",
  },
  de: {
    jumpdog: "Sprunghund",
    play: "Spielen",
    settings: "Einstellungen",
    nothingHere: "Nothing here",
    switchTheme: "Design Wechseln",
    start: "Starten",
    kuku: "Kuku",
    guest: "Gast",
    vs: "gegen",
    vsCPU: "Gegen CPU spielen",
    selectColor: "Farbe",
    selectLevel: "Ebene",
    resign: "Zurücktreten",
    undo: "Rückgängig machen",
    redo: "Wiederholen",
    hint: "Hinweis",
    cancel: "Abbrechen",
    newGame: "Neues Spiel",
    rematch: "Rückkampf",
    youWon: "Du hast gewonnen",
    youLost: "Du hast verloren",
    highlightLastMove: "Letzten Zug hervorheben",
    showLegalMoves: "Zeige legale Züge",
    showCoordinates: "Koordinaten anzeigen",
    playSounds: "Sounds abspielen",
    darkMode: "Dunkler Modus",
    boardColor: "Boardfarbe",
    language: "Sprache",
    english: "English",
    german: "Deutch",
    arabic: "العربية",
    gray: "Grau",
    blue: "Blau",
    pink: "Rosa",
    resignConfirmation: "Sind Sie sicher, dass Sie kündigen möchten?",
    takeTutorial:
      "Jumpdog has few simple rules. Would you like to take a one-time interactive guide on how to play.",
    onCaptureHelp:
      "To capture your opponent, you hop over them and land in the next square.",
    normalMoveHelp:
      "Pieces can move only one square either horizantally or vertically. No diagonal movements.",
  },
};
